import Head from 'next/head';
import { HomePage } from '../src/components/home/home-page';
import styles from '../styles/Home.module.css';


export default function Home({data}) {
  return (
    <><div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
    </div><div>
        <HomePage data={data} />
      </div></>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json');
  return {
    props: {
      data: events_categories,
    },
  };
}
